spring.application.name=aguiabranca-backend
server.port=${PORT:8080}

# Conexão MongoDB Atlas (Lê da variável de ambiente no servidor)
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/aguiabranca_db}

# Configurações do JWT
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=86400000