spring.application.name=aguiabranca-backend
server.port=8080

# Conexão MongoDB Atlas em Nuvem (Oficial)
spring.data.mongodb.uri=mongodb+srv://joaopdr924_db_user:AguiaBranca2026@cluster0.d91qif4.mongodb.net/aguiabranca_db?retryWrites=true&w=majority&appName=Cluster0

# Configurações do JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000